# Generated by Django 3.0.3 on 2020-02-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_ida', models.DateField(default=datetime.datetime.now)),
                ('data_volta', models.DateField(default=datetime.datetime.now)),
                ('data_pesquisa', models.DateField(default=datetime.datetime.now)),
                ('informacoes', models.TextField(max_length=200)),
                ('classe_viagem', models.CharField(choices=[('ECON', 'Econômica'), ('EXEC', 'Executiva'), ('PRIC', 'Primeira Classe')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
