# Generated by Django 3.0.3 on 2020-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='informacoes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
